### ISSUE TITLE
Configure Prettier, ESLint and Formatting Tools

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/demo-projects#497]
**Looking forward for reporting a security issue:**
Please report security issues by following our security policy: `https://contribute.freecodecamp.org/#/security`

**Describe the bug**
Whenever I hit the "Format with Prettier" shortcut in Visual Studio Code; it seems like the entire file is set as changed rather than just the new lines of code. 

**To Reproduce**
1. Open up the repository in Visual Studio Code 
2. Click on the american-british-translator app folder
3. Open the server file
4. Format the document with Prettier 
5. See error

**Expected behavior**
Only the lines I added should have been modified via Prettier. 

**Screenshots**
![Screenshot from GitHub Desktop](https://github.com/freeCodeCamp/demo-projects/assets/9373245/aaebbfc8-d6a5-44c7-8eaa-51582306094a)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: FireFox
 - Version: 119.0

**Additional context**
I would rather not add the endpoint for this app *before* this issue is resolved.

**Comment by raisedadead** [comment]
Thanks for reporting. The repo is missing the tooling like lint-staged and a format script like we have on the other repositories. 

Would you be interested in adding such a config? If you need inspiration, I think the main repo is a good place.
