### ISSUE TITLE
Cash Register Demo - floating-point error

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/demo-projects#559]
**Describe the bug**
Demo of the Cash Register project has issue with the floating-point error. Causing it display values with error, and in certain situations, for remaining cash to go below `$0`.

**To Reproduce**
1. Go to https://cash-register.freecodecamp.rocks
2. Enter `330` and submit.
3. Enter `10` and submit.
4. Enter `4` and submit.
5. Enter `4` and submit.

At the step 3. value below status will include the number with clear floating-point error.
After step 5. in register _Nickels_ are below `$0`.

**Expected behavior**
Cash shouldn't go below `$0`, or be displayed with more than a dozen of digits after the dot.

**Screenshots**
![image](https://github.com/freeCodeCamp/demo-projects/assets/60067306/d35b3771-fb34-444c-b9c5-de211ca748eb)

**Additional context**
- The least time-absorbing solution is adding `toFixed(2)` method to two more places:
https://github.com/freeCodeCamp/demo-projects/blob/a712591fb5cd4cb07ec0efbd8dc2578f4893df1c/apps/cash-register/public/script.js#L66
https://github.com/freeCodeCamp/demo-projects/blob/a712591fb5cd4cb07ec0efbd8dc2578f4893df1c/apps/cash-register/public/script.js#L70

- More robust option is saying _no_ to floats and changing more internals to not do calculations on floats.

**Comment by obafemitayor** [comment]
Created a PR to fix this
https://github.com/freeCodeCamp/demo-projects/pull/560
